### PR TITLE
Edit some page and add fixture of vaccine 

### PR DESCRIPTION
**Pull request by Sirikonss**
-  add logo to index page and do a little bit  animation.
- add vaccine to  fixture  (All of vaccines and its doses)
- edit css in some page.

### CODE REVIEW

**Comment by llleyelll** [comment]
Can you also improve UI on the `received` and `remove` button?
Thanks

**Review by chiiida — CHANGES_REQUESTED** [review]
Can you also improve UI on the received and remove button?
Thanks

**Comment by Sirikonss** [comment]
> Can you also improve UI on the received and remove button?
> Thanks

already edited it all

**Review by chiiida — APPROVED** [review]
Well done.

**Pull request merged**
